branch-defaults:
  main:
    environment: udagram-api-dev2
environment-defaults:
  udagram-api-dev:
    branch: main
    repository: udagram
global:
  application_name: udagram-api2
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
