version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          node --version
          java --version
          google-chrome --version
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Installing Files
          command: |
            npm run frontend:install
      - run:
          name: Back-End Installing Files
          command: |
            npm run backend:install
      - run:
          name: Front-End Building Files
          command: |
            npm run frontend:build
      - run:
          name: Back-End Building Files
          command: |
            npm run backend:build
      - run:
          name: Deploy Application
          command: |
            npm run frontend:deploy
      - run: 
          name: Deploy Code
          command: |
            npm run backend:deploy