version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
      - image: 'cimg/node:13.12-browsers'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version      
      - run:
          name: Front-End Installing Files
          command: |
            npm run frontend:install
      - run:
          name: Back-End Installing Files
          command: |
            npm run backend:install
      - run:
          name: Front-End Building Files
          command: |
            npm run frontend:build
      - run:
          name: Back-End Building Files
          command: |
            npm run backend:build
      - run:
          name: Deploy Application
          command: |
            npm run frontend:deploy