version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.6
  browser-tools: circleci/browser-tools@1.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - browser-tools/install-browser-tools
      - run: |
          node --version
          java --version
          google-chrome --version
      - run:
         name: Install pip
         command: |
           sudo apt install python3-pip
      - run:
         name: Install AWS dependencies
         command: |
           sudo pip install --upgrade awsebcli
      - run:
          name: Front-End Installing Files
          command: |
            npm run frontend:install
      - run:
          name: Back-End Installing Files
          command: |
            npm run backend:install
      - run:
          name: Front-End Building Files
          command: |
            npm run frontend:build
      - run:
          name: Back-End Building Files
          command: |
            npm run backend:build
      - run:
          name: Deploy Application
          command: |
            npm run frontend:deploy
      - run: 
          name: Deploy Code
          command: |
            npm run backend:deploy
      - run:
          name: Test
          command: |
            sudo lsof -P | grep ':8000' | awk '{print $2}' | xargs kill