version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - browser-tools/install-browser-tools
      - run: |
          node --version
          java --version
          google-chrome --version
      - run:
         name: Install pip
         command: |
           sudo apt update
           sudo docker pull iotjs/js_remote_test:0.1
           sudo docker run -t -i --privileged -v /dev/bus/usb:/dev/bus/usb iotjs/js_remote_test:0.1
      - run:
         name: Install AWS dependencies
         command: |
           sudo pip install awsebcli
      - run:
          name: Front-End Installing Files
          command: |
            npm run frontend:install
      - run:
          name: Back-End Installing Files
          command: |
            npm run backend:install
      - run:
          name: Front-End Building Files
          command: |
            npm run frontend:build
      - run:
          name: Back-End Building Files
          command: |
            npm run backend:build
      - run:
          name: Deploy Application
          command: |
            npm run frontend:deploy
      - run: 
          name: Deploy Code
          command: |
            npm run backend:deploy